# This bone description map is used to
BONE_DESC_MAP = {
    # Bone Descriptions
    # common_names: Use "." instead of "_" for improved search results
    "Hips": {
        "common_names": ["Hips", "Hip", "Pelvis"],
        "parent": None,
        "children": ["Spine", "Thigh.L", "Thigh.R"],
        "mirror": None,
    },
    "Spine": {
        "common_names": ["Spine"],
        "parent": "Hips",
        "children": ["Chest"],
        "mirror": None,
        "connected": True,
    },
    "Chest": {
        "common_names": ["Chest", "Breast Root", "Shoulder.L", "Shoulder.R"],
        "parent": "Spine",
        "children": ["Neck", "Breast Root"],
        "mirror": None,
        "connected": True,
    },
    "Neck": {
        "common_names": ["Neck"],
        "parent": "Chest",
        "children": ["Head"],
        "mirror": None,
    },
    "Head": {
        "common_names": ["Head"],
        "parent": "Neck",
        "children": ["Eye.L", "Eye.R"],
        "mirror": None,
        "connected": True,
    },
    "Eye.L": {
        "common_names": ["Eye.L", "Left Eye"],
        "parent": "Head",
        "children": None,
        "mirror": "Eye.R",
    },
    "Eye.R": {
        "common_names": ["Eye.R", "Right Eye"],
        "parent": "Head",
        "children": None,
        "mirror": "Eye.L",
    },
    "Breast Root": {
        "common_names": ["Breast Root", "Boob Root"],
        "parent": "Chest",
        "children": ["Breast.R", "Breast.L"],
        "mirror": None,
        "optional": True,
    },
    "Breast.L": {
        "common_names": ["Breast", "BreastUpper2_L", "Left Breast"],
        "parent": "Breast Root",
        "children": None,
        "mirror": "Breast.R",
        "optional": True,
    },
    "Breast.R": {
        "common_names": ["Breast", "BreastUpper2_R", "Right Breast"],
        "parent": "Breast Root",
        "children": None,
        "mirror": "Breast.L",
        "optional": True,
    },
    "Upper Leg.L": {
        "common_names": ["Upper Leg.L", "Thigh.L", "Leg.L", "Left Leg"],
        "parent": "Hips",
        "children": ["Lower Leg.L"],
        "mirror": "Upper Leg.R",
        "roll": 180,
    },
    "Lower Leg.L": {
        "common_names": ["Lower Leg.L", "Knee.L", "Left Knee"],
        "parent": "Upper Leg.L",
        "children": ["Foot.L"],
        "mirror": "Lower Leg.R",
        "connected": True,
        "roll": 180,
    },
    "Foot.L": {
        "common_names": ["Foot.L", "Ankle.L", "Left Ankle", "Left Foot"],
        "parent": "Lower Leg.L",
        "children": ["Toes.L"],
        "mirror": "Foot.R",
        "connected": True,
    },
    "Toes.L": {
        "common_names": ["Toes.L", "Toe.L", "Left Toe"],
        "parent": "Foot.L",
        "children": None,
        "mirror": "Toes.R",
    },
    "Upper Leg.R": {
        "common_names": ["Upper Leg.R", "Thigh.R", "Leg.R", "Right Leg"],
        "parent": "Hips",
        "children": ["Lower Leg.R"],
        "mirror": "Upper Leg.L",
        "roll": 180,
    },
    "Lower Leg.R": {
        "common_names": ["Lower Leg.R", "Knee.R", "Right Knee"],
        "parent": "Upper Leg.R",
        "children": ["Foot.R"],
        "mirror": "Lower Leg.L",
        "connected": True,
        "roll": 180,
    },
    "Foot.R": {
        "common_names": ["Foot.R", "Ankle.R", "Right Ankle", "Right Foot"],
        "parent": "Lower Leg.R",
        "children": ["Toes.R"],
        "mirror": "Foot.L",
        "connected": True,
    },
    "Toes.R": {
        "common_names": ["Toes.R", "Toe.R", "Right Toe"],
        "parent": "Foot.R",
        "children": None,
        "mirror": "Toes.L",
    },
    "Shoulder.L": {
        "common_names": ["Shoulder.L", "Left Shoulder"],
        "parent": "Chest",
        "children": ["Arm.L"],
        "mirror": "Shoulder.R",
    },
    "Upper Arm.L": {
        "common_names": ["Upper Arm.L", "Arm.L", "Left Arm"],
        "parent": "Shoulder.L",
        "children": ["Lower Arm.L"],
        "mirror": "Upper Arm.R",
        "connected": True,
    },
    "Lower Arm.L": {
        "common_names": ["Lower Arm.L", "Elbow.L", "Left Elbow"],
        "parent": "Upper Arm.L",
        "children": ["Hand.L"],
        "mirror": "Lower Arm.R",
        "connected": True,
        "roll": -90,
    },
    "Hand.L": {
        "common_names": ["Hand.L", "Wrist.L", "Left Wrist"],
        "parent": "Lower Arm.L",
        "children": [
            "Thumb 1.L",
            "Little Finger 1.L",
            "Ring Finger 1.L",
            "Middle Finger 1.L",
            "Index Finger 1.L",
        ],
        "mirror": "Hand.R",
        "connected": True,
    },
    "Shoulder.R": {
        "common_names": ["Shoulder.R", "Right Shoulder"],
        "parent": "Chest",
        "children": ["Arm.R"],
        "mirror": "Shoulder.L",
    },
    "Upper Arm.R": {
        "common_names": ["Upper Arm.R", "Arm.R", "Right Arm"],
        "parent": "Shoulder.R",
        "children": ["Lower Arm.R"],
        "mirror": "Upper Arm.L",
        "connected": True,
    },
    "Lower Arm.R": {
        "common_names": ["Lower Arm.R", "Elbow.R", "Right Elbow"],
        "parent": "Upper Arm.R",
        "children": ["Hand.R"],
        "mirror": "Lower Arm.L",
        "connected": True,
        "roll": 90,
    },
    "Hand.R": {
        "common_names": ["Hand.R", "Wrist.R", "Right Wrist"],
        "parent": "Lower Arm.R",
        "children": [
            "Thumb 1.R",
            "Little Finger 1.R",
            "Ring Finger 1.R",
            "Middle Finger 1.R",
            "Index Finger 1.R",
        ],
        "mirror": "Hand.L",
        "connected": True,
    },
    "Thumb 1.L": {
        "common_names": ["Thumb0.L", "Thumb Proximal.L"],
        "parent": "Hand.L",
        "children": ["Thumb 2.L"],
        "mirror": "Thumb 1.R",
        "roll": 90,
    },
    "Thumb 2.L": {
        "common_names": ["Thumb1.L", "Thumb Intermediate.L"],
        "parent": "Thumb 1.L",
        "children": ["Thumb 3.L"],
        "mirror": "Thumb 2.R",
        "connected": True,
        "roll": 90,
    },
    "Thumb 3.L": {
        "common_names": ["Thumb2.L", "Thumb Distal.L"],
        "parent": "Thumb 2.L",
        "children": None,
        "mirror": "Thumb 3.R",
        "connected": True,
        "roll": 90,
    },
    "Index Finger 1.L": {
        "common_names": ["IndexFinger1.L", "Index Finger Left", "Index Proximal.L"],
        "parent": "Hand.L",
        "children": ["Index Finger 2.L"],
        "mirror": "Index Finger 1.R",
    },
    "Index Finger 2.L": {
        "common_names": ["IndexFinger2.L", "Index Finger Left", "Index Intermediate.L"],
        "parent": "Index Finger 1.L",
        "children": ["Index Finger 3.L"],
        "mirror": "Index Finger 2.R",
        "connected": True,
    },
    "Index Finger 3.L": {
        "common_names": ["IndexFinger3.L", "Index Finger Left", "Index Distal.L"],
        "parent": "Index Finger 2.L",
        "children": None,
        "mirror": "Index Finger 3.R",
        "connected": True,
    },
    "Middle Finger 1.L": {
        "common_names": ["MiddleFinger1.L", "Middle Finger Left", "Middle Proximal.L"],
        "parent": "Hand.L",
        "children": ["Middle Finger 2.L"],
        "mirror": "Middle Finger 1.R",
    },
    "Middle Finger 2.L": {
        "common_names": [
            "MiddleFinger2.L",
            "Middle Finger Left",
            "Middle Intermediate.L",
        ],
        "parent": "Middle Finger 1.L",
        "children": ["Middle Finger 3.L"],
        "mirror": "Middle Finger 2.R",
        "connected": True,
    },
    "Middle Finger 3.L": {
        "common_names": ["MiddleFinger3.L", "Middle Finger Left", "Middle Distal.L"],
        "parent": "Middle Finger 2.L",
        "children": None,
        "mirror": "Middle Finger 3.R",
        "connected": True,
    },
    "Ring Finger 1.L": {
        "common_names": ["RingFinger1.L", "Ring Finger Left", "Ring Proximal.L"],
        "parent": "Hand.L",
        "children": ["Ring Finger 2.L"],
        "mirror": "Ring Finger 1.R",
    },
    "Ring Finger 2.L": {
        "common_names": ["RingFinger2.L", "Ring Finger Left", "Ring Intermediate.L"],
        "parent": "Ring Finger 1.L",
        "children": ["Ring Finger 3.L"],
        "mirror": "Ring Finger 2.R",
        "connected": True,
    },
    "Ring Finger 3.L": {
        "common_names": ["RingFinger3.L", "Ring Finger Left", "Ring Distal.L"],
        "parent": "Ring Finger 2.L",
        "children": None,
        "mirror": "Ring Finger 3.R",
        "connected": True,
    },
    "Little Finger 1.L": {
        "common_names": ["LittleFinger1.L", "Little Finger Left", "Little Proximal.L"],
        "parent": "Hand.L",
        "children": ["Little Finger 2.L"],
        "mirror": "Little Finger 1.R",
    },
    "Little Finger 2.L": {
        "common_names": [
            "LittleFinger2.L",
            "Little Finger Left",
            "Little Intermediate.L",
        ],
        "parent": "Little Finger 1.L",
        "children": ["Little Finger 3.L"],
        "mirror": "Little Finger 2.R",
        "connected": True,
    },
    "Little Finger 3.L": {
        "common_names": ["LittleFinger3.L", "Little Finger Left", "Little Distal.L"],
        "parent": "Little Finger 2.L",
        "children": None,
        "mirror": "Little Finger 3.R",
        "connected": True,
    },
    "Thumb 1.R": {
        "common_names": ["Thumb0.R", "Thumb Proximal.R"],
        "parent": "Hand.R",
        "children": ["Thumb 2.R"],
        "mirror": "Thumb 1.L",
        "roll": -90,
    },
    "Thumb 2.R": {
        "common_names": ["Thumb1.R", "Thumb Intermediate.R"],
        "parent": "Thumb 1.R",
        "children": ["Thumb 3.R"],
        "mirror": "Thumb 2.L",
        "connected": True,
        "roll": -90,
    },
    "Thumb 3.R": {
        "common_names": ["Thumb2.R", "Thumb Distal.R"],
        "parent": "Thumb 2.R",
        "children": None,
        "mirror": "Thumb 3.L",
        "connected": True,
        "roll": -90,
    },
    "Index Finger 1.R": {
        "common_names": ["IndexFinger1.R", "Index Finger Right", "Index Proximal.R"],
        "parent": "Hand.R",
        "children": ["Index Finger 2.R"],
        "mirror": "Index Finger 1.L",
    },
    "Index Finger 2.R": {
        "common_names": [
            "IndexFinger2.R",
            "Index Finger Right",
            "Index Intermediate.R",
        ],
        "parent": "Index Finger 1.R",
        "children": ["Index Finger 3.R"],
        "mirror": "Index Finger 2.L",
        "connected": True,
    },
    "Index Finger 3.R": {
        "common_names": ["IndexFinger3.R", "Index Finger Right", "Index Distal.R"],
        "parent": "Index Finger 2.R",
        "children": None,
        "mirror": "Index Finger 3.L",
        "connected": True,
    },
    "Middle Finger 1.R": {
        "common_names": ["MiddleFinger1.R", "Middle Finger Right", "Middle Proximal.R"],
        "parent": "Hand.R",
        "children": ["Middle Finger 2.R"],
        "mirror": "Middle Finger 1.L",
    },
    "Middle Finger 2.R": {
        "common_names": [
            "MiddleFinger2.R",
            "Middle Finger Right",
            "Middle Intermediate.R",
        ],
        "parent": "Middle Finger 1.R",
        "children": ["Middle Finger 3.R"],
        "mirror": "Middle Finger 2.L",
        "connected": True,
    },
    "Middle Finger 3.R": {
        "common_names": ["MiddleFinger3.R", "Middle Finger Right", "Middle Distal.R"],
        "parent": "Middle Finger 2.R",
        "children": None,
        "mirror": "Middle Finger 3.L",
        "connected": True,
    },
    "Ring Finger 1.R": {
        "common_names": ["RingFinger1.R", "Ring Finger Right", "Ring Proximal.R"],
        "parent": "Hand.R",
        "children": ["Ring Finger 2.R"],
        "mirror": "Ring Finger 1.L",
    },
    "Ring Finger 2.R": {
        "common_names": ["RingFinger2.R", "Ring Finger Right", "Ring Intermediate.R"],
        "parent": "Ring Finger 1.R",
        "children": ["Ring Finger 3.R"],
        "mirror": "Ring Finger 2.L",
        "connected": True,
    },
    "Ring Finger 3.R": {
        "common_names": ["RingFinger3.R", "Ring Finger Right", "Ring Distal.R"],
        "parent": "Ring Finger 2.R",
        "children": None,
        "mirror": "Ring Finger 3.L",
        "connected": True,
    },
    "Little Finger 1.R": {
        "common_names": ["LittleFinger1.R", "Little Finger Right", "Little Proximal.R"],
        "parent": "Hand.R",
        "children": ["Little Finger 2.R"],
        "mirror": "Little Finger 1.L",
    },
    "Little Finger 2.R": {
        "common_names": [
            "LittleFinger2.R",
            "Little Finger Right",
            "Little Intermediate.R",
        ],
        "parent": "Little Finger 1.R",
        "children": ["Little Finger 3.R"],
        "mirror": "Little Finger 2.L",
        "connected": True,
    },
    "Little Finger 3.R": {
        "common_names": ["LittleFinger3.R", "Little Finger Right", "Little Distal.R"],
        "parent": "Little Finger 2.R",
        "children": None,
        "mirror": "Little Finger 3.L",
        "connected": True,
    },
}
