EXPORT_COLLECTION = "Export"
PROP_AVATAR_NAME = "avatar_name"
PROP_AVATAR_EXPORT_PATH = "avatar_export_path"
PROP_AVATAR_LAYERS = "avatar_layers"
A_POSE_SHOULDER_ANGLE = 15
SHAPE_KEY_TOLERANCE = 0.001

VERSION = (0, 0, 0)
